env:
  node: true

plugins: [eslint-plugin-import]

extends:
  - eslint:recommended
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions:
    - error
    - js: always
  no-unused-vars: ['warn', { 'vars': 'all', 'args': 'after-used', 'ignoreRestSiblings': false }]
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }] # разрешает подчёркивание в именах только для двух констант
